/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './angular-module-starter.module';
import * as import2 from '@angular/core/src/di/injector';
import * as import3 from './angular-module-starter.service';
class AngularModuleStarterModuleInjector extends import0.NgModuleInjector<import1.AngularModuleStarterModule> {
  _AngularModuleStarterModule_0:import1.AngularModuleStarterModule;
  __AngularModuleStarterService_1:any;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _AngularModuleStarterService_1():any {
    if ((this.__AngularModuleStarterService_1 == null)) { (this.__AngularModuleStarterService_1 = import1.asyncLocalStorageFactory()); }
    return this.__AngularModuleStarterService_1;
  }
  createInternal():import1.AngularModuleStarterModule {
    this._AngularModuleStarterModule_0 = new import1.AngularModuleStarterModule();
    return this._AngularModuleStarterModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AngularModuleStarterModule)) { return this._AngularModuleStarterModule_0; }
    if ((token === import3.AngularModuleStarterService)) { return this._AngularModuleStarterService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AngularModuleStarterModuleNgFactory:import0.NgModuleFactory<import1.AngularModuleStarterModule> = new import0.NgModuleFactory(AngularModuleStarterModuleInjector,import1.AngularModuleStarterModule);